# config/schedule.yml
get_currencies_rates_cron_job:
  cron: "* * * * *"
  class: "GetCurrenciesRatesCronJob"
  active_job: 'true'
  queue_name_prefix: <%= "#{Rails.env}" %>
  queue: <%= Rails.env.production? ? "#{Rails.env}_light" : "#{Rails.env}" %>
